import type { Layout } from './types';

/** Dvorak moves punctuation as well as letters, so it's entered in full. */
export const dvorak: Layout = {
	id: 'dvorak',
	label: 'Dvorak',
	keys: {
		Backquote: { base: '`', shift: '~' },
		Digit1: { base: '1', shift: '!' },
		Digit2: { base: '2', shift: '@' },
		Digit3: { base: '3', shift: '#' },
		Digit4: { base: '4', shift: '$' },
		Digit5: { base: '5', shift: '%' },
		Digit6: { base: '6', shift: '^' },
		Digit7: { base: '7', shift: '&' },
		Digit8: { base: '8', shift: '*' },
		Digit9: { base: '9', shift: '(' },
		Digit0: { base: '0', shift: ')' },
		Minus: { base: '[', shift: '{' },
		Equal: { base: ']', shift: '}' },
		KeyQ: { base: "'", shift: '"' },
		KeyW: { base: ',', shift: '<' },
		KeyE: { base: '.', shift: '>' },
		KeyR: { base: 'p', shift: 'P' },
		KeyT: { base: 'y', shift: 'Y' },
		KeyY: { base: 'f', shift: 'F' },
		KeyU: { base: 'g', shift: 'G' },
		KeyI: { base: 'c', shift: 'C' },
		KeyO: { base: 'r', shift: 'R' },
		KeyP: { base: 'l', shift: 'L' },
		BracketLeft: { base: '/', shift: '?' },
		BracketRight: { base: '=', shift: '+' },
		Backslash: { base: '\\', shift: '|' },
		KeyA: { base: 'a', shift: 'A' },
		KeyS: { base: 'o', shift: 'O' },
		KeyD: { base: 'e', shift: 'E' },
		KeyF: { base: 'u', shift: 'U' },
		KeyG: { base: 'i', shift: 'I' },
		KeyH: { base: 'd', shift: 'D' },
		KeyJ: { base: 'h', shift: 'H' },
		KeyK: { base: 't', shift: 'T' },
		KeyL: { base: 'n', shift: 'N' },
		Semicolon: { base: 's', shift: 'S' },
		Quote: { base: '-', shift: '_' },
		KeyZ: { base: ';', shift: ':' },
		KeyX: { base: 'q', shift: 'Q' },
		KeyC: { base: 'j', shift: 'J' },
		KeyV: { base: 'k', shift: 'K' },
		KeyB: { base: 'x', shift: 'X' },
		KeyN: { base: 'b', shift: 'B' },
		KeyM: { base: 'm', shift: 'M' },
		Comma: { base: 'w', shift: 'W' },
		Period: { base: 'v', shift: 'V' },
		Slash: { base: 'z', shift: 'Z' },
		Space: { base: ' ', shift: ' ' }
	}
};
